### ISSUE TITLE
doubt: loglevel per watcher

### ISSUE THREAD

**Issue by paulocheque** [circus-tent/circus#1029]
I would like to configure one `loglevel` **per watcher**. is that possible? I didn't find anything in docs or google.

Thanks in advance

**Comment by biozz** [comment]
Hi @paulocheque!

I guess you are referring to `circus.loglevel` setting in the first place. Just to make sure we are on the same page: this setting is used to configure the Circus logger. Circus logger is responsible for all of the internal events logging, like arbiter start/restart, watcher errors, etc. Those events and their levels are predefined and should not be changed.

If you want your watchers to output with the different level you will have to implement it in your program and configure `stdout_stream` and `stderr_stream` appropriately.

I know this issue is 3 years old and you might have solved this somehow, so I am closing it due to inactivity. Please feel free to reopen.
