### ISSUE TITLE
Lock down tornado version

### ISSUE THREAD

**Issue by swarajban** [circus-tent/circus#1056]
[Tornado](https://github.com/tornadoweb/tornado/releases/tag/v5.0.0) just released a new major version (5), and this breaks circus (circus fails to start). We should lock down the tornado version to 4.x.x to prevent this

Circus error with new `tornado`
```
2018-03-05 18:35:09 circus[65281] [INFO] Starting master on pid 65281
2018-03-05 18:35:09 circus[65281] [ERROR] exception __init__() takes 3 positional arguments but 4 were given caught
```

**Comment by swarajban** [comment]
Looks like https://github.com/circus-tent/circus/pull/1052 fixes issue

**Comment by sboisson** [comment]
This would solve #1059

**Comment by naymesh** [comment]
Hello! Circus Team. I trying to use Circus as replacement for supervisord as supervisord does not have a Python3 compatible release yet.

I was hit by https://github.com/circus-tent/circus/issues/1057 which lead me to this issue.

Is there an ETA on when the fix for this issue might be released?  Thanks!

**Comment by biozz** [comment]
`master` branch is now compatible with newer versions of `tornado`. Please follow #1130 for the release dates.
