### ISSUE TITLE
mem_info not reliable

### ISSUE THREAD

**Issue by maingoh** [circus-tent/circus#1127]
The human friendly representation gives integer representation instead of float which gives unreliable stats.
```
>>> from circus.util import bytes2human
>>> bytes2human(1024 * 1024 * 2047)
'1G'
>>> bytes2human(1024 * 1024 * 2048)
'2G'
```

The first example should return `1.99G` ideally. This is not critical when talking about megas but when we start talking about gigas or more it gets problematic.

Also why not always give a MiB representation in float (not string) ?

**Comment by biozz** [comment]
Adding 2 decimal places without rounding to `bytes2human` seems quite simple, I can submit a PR for that, if it is OK with you.

Just to clarify:

```
>>> from circus.util import bytes2human
>>> bytes2human(1024 * 1024 * 2047)
'1.99G'
>>> bytes2human(1024 * 1024 * 2048)
'2.00G'
```
The second one should return `2.00G` or `2G`?

> Also why not always give a MiB representation in float (not string) ?

It depends. For example, `htop` shows `G` only because the column is 5 symbols wide and it can't fit `M` representation anymore. 

What is your use case?

<img width="484" alt="Screenshot 2020-03-30 at 09 51 51" src="https://user-images.githubusercontent.com/3424811/77883626-2d48c680-726c-11ea-9162-a0e089c193c0.png">

**Comment by maingoh** [comment]
It is ok for me :)

> The second one should return 2.00G or 2G?

Both are fine for me as long as the `human2bytes` can convert back without loosing much precision.

> What is your use case?

My use case is actually not to get something human readable but more to monitor watchers over time and eventually draw graphs so a float representation would be preferable but I can deal with the human representation.
