### ISSUE TITLE
Make a new release supporting Python 3.10

### ISSUE THREAD

**Issue by espenfl** [circus-tent/circus#1190]
Would it be possible to make a new release supporting Python 3.10, with this fix included: https://github.com/circus-tent/circus/pull/1170? Thanks for considering.

**Comment by espenfl** [comment]
@k4nar Have you had time to look into this? Would be sweet to get a bugfix release out now that Python 3.10 is geting picked up as the default by a few distributions.

**Comment by sphuber** [comment]
@k4nar it would be great if you or someone else could have a look at this. This is currently blocking our project https://github.com/aiidateam/aiida-core and its entire plugin ecosystem. Is there anything blocking making the release? Let me know if there is a way I can lend a hand. Thanks a lot.

**Comment by sphuber** [comment]
I have just pushed a new release `v0.17.2` that includes the fix for #1170 (https://pypi.org/project/circus/0.17.2/) . The tests are not actually running on Python 3.10 yet, because they are still running on `nose` which doesn't support it, and it has been abandoned: https://github.com/nose-devs/nose/issues/1099

I opened https://github.com/circus-tent/circus/issues/1192 and will move to `pytest`. Once that is done, I can add official support for Python 3.10 with tests running against this version in the CI workflow.
