### ISSUE TITLE
add a "process" bool option in the plugins

### ISSUE THREAD

**Issue by tarekziade** [circus-tent/circus#140]
- create a circusd-plugin script that can be used to run a plugin, given all its options
- add a "process" option

when process is True, CIrcus add a watcher that runs a circusd-plugin script against the plugin. The watcher name == the plugin name.

This will allow plugins to run in their own process if they want

**Comment by pconerly** [comment]
@tarekziade yo, is there a reason you wrote `_cfg2str` and `_str2cfg` instead of using JSON?

I'm trying to add `[env]` to plugins, which means I have a nested dictionary to send to the plugins, and it of course it's breaking. :)  

```
/Users/peterconerly/.virtualenvs/derp/bin/python -c 'from circus import plugins;plugins.main()' --endpoint tcp://127.0.0.1:50500 --pubsub tcp://127.0.0.1:50501 --config copy_env:True:::name:foobar:::env:{'PYTHONPATH': '/Users/peterconerly/code/circus/circus/tests/config'} plugins_uniquename.my_plugin.MyPlugin
```

If there's a good reason not to use JSON then I'd love to hear it :)
