### ISSUE TITLE
Fabric with Circus issue

### ISSUE THREAD

**Issue by jnosal** [circus-tent/circus#733]
So i'm using fabric to run deployment procedure. Besides few operations one of this would be to restart circus by simply invokinf ./circusctl restart command, in case it's a first run script would start circus daemon.

My problem is:
When I run those scripts from the server itself they work like charm, but when I run them via fabric they'd sometimes (2 out of 10 tries) so i'm forced to connect to my machine and  do stuff manually.

That's the first project I decided to use circus - mainly because of its python3 support but appreciate the docs and design as well ;)

Any advice appreciated

**Comment by cgarciaarano** [comment]
I'm using Fabric to manage our Circus instances and everything works, everytime. I bet is a Fabric issue or misconfiguration.

Try this simple function in Fabric, it should work

```python
@task
def status():
	return run('circusctl status')
```
And run it with fab:
```
fab status -H $HOST
```

If your script fails when you restart Circus daemon, then your problem is probably [this] (http://docs.fabfile.org/en/1.5/faq.html#init-scripts-don-t-work). There are oher related problems that could be solved using [nohup](https://github.com/fabric/fabric/issues/395)

**Comment by k4nar** [comment]
Thanks @cgarciaarano !

As we don't have any news from @jnosal and Circus seems to run fine with Fabric, I'll close this issue for now.
