### ISSUE TITLE
why is synchronized global

### ISSUE THREAD

**Issue by matleh** [circus-tent/circus#900]
Several commands (e.g. `stop`) are `synchronized` which means, that only one of them can run at the same time. This has the effect that if I issue several `stop` commands with `waiting=False`, the latter ones will fail since the first one is still running.

Is it really necessary for `synchronized` to be global or could it be sufficient to work on a per watcher level? This way, I could issue several stop commands with `waiting=False` for different watchers.

My use case is the following: I use circus as a process manager for an application which consists of several processes (obviously). Over a REST-API, I can stop (and later start) groups of processes - so I want the REST-call to return as quick as possible (`waiting=False`). The client can poll the result later with another REST-call.

**Comment by k4nar** [comment]
I never quite understood why this decorator was used all over the place. I think we'll have to summon @tarekziade for that :) .

I don't want to mess with it without understanding perfectly why it's there, as race-conditions can be hard to find, even in the tests.

**Comment by tarekziade** [comment]
Yeah this is delicate: this decorator is a global lock to avoid messy situations where you ask Circus two conflicting actions that would result in a bad internal state of the arbiter. We can probably make it less global in some places.

Stopping several watchers in parallel is technically doable of course, but we need to review the arbiter code in order to verify that when this happens, the code is not making the assumption that the internal state cannot be modified by two actions in parallel.  That includes all the events that are regularly waking up to work with the watchers list.

**Comment by matleh** [comment]
#776 is about the same problem.
My use-case could also be covered with the "wildcard watcher addressing functionality" which is given as a solution there.

**Comment by k4nar** [comment]
I'm closing this as your specific use-case has been fixed.

However, let's keep the discussion about conflict errors in #987 .
